### ISSUE TITLE
cryptography.x509 backend

### ISSUE THREAD

**Issue by mithrandi** [pyca/service_identity#14]
I'd like something I can pass a `cryptography.x509.Certificate` and hostname to.

**Comment by hynek** [comment]
Totally agreed!  Volunteers? :)

**Comment by mithrandi** [comment]
I'll probably provide a PR at some point if someone doesn't beat me to it, have a few other yaks on this particular stack to shave first.

**Comment by hynek** [comment]
IIRC, all you have to do is to extract the relevant names from the certificate.  Mostly a SMOP.
