### ISSUE TITLE
Wildcard validation not working for non FQDN / direct hostname

### ISSUE THREAD

**Issue by adiroiban** [pyca/service_identity#22]
I am doing a simple test in which the target hosname is just 'xps' and it fails.

I know that in public you might never hit this error, but for private networks, you can do whatever you want and I would be nice if I don't have to add extra validation before calling service_identity.

Thanks!

----------------

The high level code
```
actual
(Pdb) [DNSPattern(pattern='*.example.com'), DNSPattern(pattern='*.sub.example.org')]
self._remote_id
(Pdb) DNS_ID(hostname='xps')
verify_service_identity(cert_patterns=actual,obligatory_ids=[self._remote_id],optional_ids=[])
(Pdb) *** ValueError: need more than 1 value to unpack
```

if I go deeper 

```
cert_pattern
(Pdb) '*.example.com'
actual_hostname
(Pdb) 'xps'

  	    if b'*' in cert_pattern:
  	        cert_head, cert_tail = cert_pattern.split(b".", 1)
	        actual_head, actual_tail = actual_hostname.split(b".", 1)

```

**Comment by hynek** [comment]
What have the RFCs to say about that?

**Comment by tiran** [comment]
RFC 6125 refers to wildcard as ** left-most label** multiple times but never to wildcard as only label. In section 2.2 DNS Domain Names are defined as **fully qualified DNS domain**, too. This implies that a SAN or CN can't be a single host wildcard.

In general it's a bad idea to use a non-qualified hostname or short alias for hostname verification.

**Comment by hynek** [comment]
Sounds like `xps.local` is the answer here?

**Comment by adiroiban** [comment]
Thanks. I think there is no point in working on this.
I only wanted to raise this in case others find it an issue... since is a non-issue no need to worry about it just to support a testing / non-production env
