### ISSUE TITLE
Segmentation fault upon installing service_identity

### ISSUE THREAD

**Issue by wsdookadr** [pyca/service_identity#28]
I'm using the following:

    user@garage2:/$ pip3 --version
    pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
    user@garage2:/$ python3 --version
    Python 3.6.5

This is the output:

    user@garage2:~/$ pip3 install --user service_identity
    Collecting service_identity
      Using cached https://files.pythonhosted.org/packages/29/fa/995e364220979e577e7ca232440961db0bf996b6edaf586a7d1bd14d81f1/service_identity-17.0.0-py2.py3-none-any.whl
    Collecting pyopenssl>=0.12 (from service_identity)
      Using cached https://files.pythonhosted.org/packages/96/af/9d29e6bd40823061aea2e0574ccb2fcf72bfd6130ce53d32773ec375458c/pyOpenSSL-18.0.0-py2.py3-none-any.whl
    Collecting attrs (from service_identity)
      Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
    Collecting pyasn1 (from service_identity)
      Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
    Collecting pyasn1-modules (from service_identity)
      Using cached https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl
    Collecting cryptography>=2.2.1 (from pyopenssl>=0.12->service_identity)
      Using cached https://files.pythonhosted.org/packages/59/32/92cade62c645756a83598edf56289e9b19aae5370642a7ce690cd06bc72f/cryptography-2.3.1-cp34-abi3-manylinux1_x86_64.whl
    Collecting six>=1.5.2 (from pyopenssl>=0.12->service_identity)
      Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
    Collecting cffi!=1.11.3,>=1.7 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity)
      Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
    Collecting idna>=2.1 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity)
      Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
    Collecting asn1crypto>=0.21.0 (from cryptography>=2.2.1->pyopenssl>=0.12->service_identity)
      Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
    Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography>=2.2.1->pyopenssl>=0.12->service_identity)
    Installing collected packages: six, pycparser, cffi, idna, asn1crypto, cryptography, pyopenssl, attrs, pyasn1, pyasn1-modules, service-identity
    Successfully installed asn1crypto-0.24.0 attrs-18.2.0 cffi-1.11.5 cryptography-2.3.1 idna-2.7 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycparser-2.19 pyopenssl-18.0.0 service-identity-17.0.0 six-1.11.0
    Segmentation fault (core dumped)

**Comment by reaperhulk** [comment]
Update your pip and try this again. I suspect this is a (long fixed) pip bug.

**Comment by wsdookadr** [comment]
@reaperhulk yup, true
