### ISSUE TITLE
emit a warning when matching the commonName of a certificate

### ISSUE THREAD

**Issue by alex** [pyca/service_identity#9]
RFC2818 has said that using commonName for service identity is a legacy thing, and the CAB forum baseline requirements has required a subjectAltName since 2012. We should emit a warning when commonName is relied upon for validation.

urllib3 already emits a warning if the certificate does not have SANs

**Comment by hynek** [comment]
Isn’t that just about raising a warning in this block: https://github.com/pyca/service_identity/blob/master/service_identity/pyopenssl.py#L73 ?
